name: lisbetenv
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  # Core
  - python=3.12
  - pip
  - setuptools
  - wheel
  # PyTorch family
  - pytorch
  - torchvision
  # CUDA runtime (Windows & Linux only)
  - pytorch-cuda=12.8
  # LISBET
  - pip:
      - lisbet
